name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Default Scheme
        run: |
          pod install
          xcodebuild build -workspace Yelm.ProjectX.xcworkspace -scheme Yelm.ProjectX -allowProvisioningUpdates
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          pod install
          xcodebuild build -workspace Yelm.ProjectX.xcworkspace -scheme Yelm.ProjectX -allowProvisioningUpdates
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          pod install
          xcodebuild build -workspace Yelm.ProjectX.xcworkspace -scheme Yelm.ProjectX -allowProvisioningUpdates
